[window]
dimensions = { columns = 120, lines = 40 }
padding = { x = 5, y = 5 }
decorations = "Full"
opacity = 0.9
[selection]
save_to_clipboard = true
[cursor]
style = { shape = "Block", blinking = "Off" }
[mouse]
hide_when_typing = true
[font]
normal = { family = "Hack  Nerd Font Mono", style = "Regular" }
bold = { family = "Hack  Nerd Font Mono", style = "Bold" }
italic = { family = "Hack  Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Hack  Nerd Font Mono", style = "Bold Italic" }
size = 12
